# Generated by Django 3.2.5 on 2021-08-02 01:22

from django.db import migrations, models
import filmes.models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=filmes.models.upload_image_filme),
        ),
    ]
